language: r
cache: packages

notifications:
  email:
    recipients:
     - alerts@jumpingrivers.support
    on_success: change
    on_failure: change

env:
  global:
    - ALLOWED_NOTES=1

before_install:
  - sudo apt-get install -y libudunits2-dev libgdal-dev ghostscript

before_script:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/test_deploy.sh
  - bash test_deploy.sh && rm test_deploy.sh

script:
  - Rscript -e "source('https://raw.githubusercontent.com/jr-packages/drat/master/script.R')"

after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
